name: test

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   hmm:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: cloudfoundry/cloud_controller_ng
          ref: terrible-things-to-get-to-ruby-3.3
      - name: List
        run: |
            ls
            ls -a
            pwd
      - name: docker compose
        uses: adambirds/docker-compose-action@v1.3.0
        with:
         compose-file: "docker-compose.yml"
