name: test-with-deps

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #services:
      # postgres:
      #   image: postgres:16-alpine
      #   env:
      #     POSTGRES_PASSWORD: supersecret
      #   ports:
      #   - 5432:5432
      
      # mysql:
      #   image: mysql:8.2
      #   env:
      #     MYSQL_ROOT_PASSWORD: supersecret
      #   ports:
      #   - 3306:3306
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: cloudfoundry/cloud_controller_ng
          ref: 0906849122689b28c9ef4c1b5cec47223db8a328
      - name: trying tmp
        run : |
           pwd
           ls
           mkdir -p tmp
           cp -a config/cloud_controller.yml tmp/cloud_controller.yml
           echo ------
           echo copied
           echo -----
           ls
           echo ------
           sudo add-apt-repository ppa:rmescandon/yq
           sudo apt update
           sudo apt install yq -y
           yq -i e '.external_domain="localhost"' tmp/cloud_controller.yml

      - name: docker compose
        uses: adambirds/docker-compose-action@v1.3.0
        with:
         compose-file: |
           docker-compose.yml
         services: |
            postgres
            mysql
            catsbroker
            uaa
            minio
            nginx
      - name: Installing Packages
        run: |
           PACKAGES="cf8-cli postgresql-client postgresql-client-common mariadb-client"
           wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
           echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
           sudo apt-get update
           export DEBIAN_FRONTEND="noninteractive" && echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
           sudo apt-get install -o Dpkg::Options::="--force-overwrite" $PACKAGES -y
           sudo apt install -o Dpkg::Options::="--force-overwrite" git curl libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev -y
           wget "$(curl -s https://api.github.com/repos/cloudfoundry/credhub-cli/releases/latest |
           jq -r '.assets[] | select(.name|match("credhub-linux.*")) | .browser_download_url')" -O /tmp/credhub.tar.gz
           cd /tmp
           sudo tar -xzf /tmp/credhub.tar.gz && sudo rm -f /tmp/credhub.tar.gz && sudo mv /tmp/credhub /usr/bin
      - uses: ruby/setup-ruby@v1.172.0
        # with:
          #bundler-cache: true 
      
      - name: Initializing stuff
        run: |
           cp .devcontainer/scripts/setupDevelopmentEnvironment.sh .
           pwd
           ls
           sudo ./setupDevelopmentEnvironment.sh
           
          
